[package]
name = "wser-python"
version = "0.1.0"
edition = "2021"

[lib]
name = "wser"
crate-type = ["cdylib"]

[dependencies]
wser = { path = ".." }
pyo3 = { version = "0.22", features = ["extension-module"] }
